/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "##REGION_PLACEHOLDER##",
    "aws_appsync_graphqlEndpoint": "##GRAPHQL_ENDPOINT_PLACEHOLDER##",
    "aws_appsync_region": "##REGION_PLACEHOLDER##",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "##API_KEY_PLACEHOLDER##"
};


export default awsmobile;
